<a href="https://colab.research.google.com/github/yathishlax/Fake-news-classifier-using-LSTM/blob/master/FakeNewsClassifierUsingLSTM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Fake News Classifier Using LSTM

Dataset: https://www.kaggle.com/c/fake-news/data#

Lets import panadas library

In [0]:
import pandas as pd

Uploading file from local drive to google colab

In [11]:
from google.colab import files
uploaded = files.upload()

Saving train-lstm.csv to train-lstm (1).csv


In [0]:
df = pd.read_csv('train-lstm (1).csv')

In [15]:
df.head()

id  ... label
0   0  ...     1
1   1  ...     0
2   2  ...     1
3   3  ...     1
4   4  ...     1

[5 rows x 5 columns]

In [0]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

Since these are text data and nan values are to be removed

In [0]:
###Drop Nan Values
df=df.dropna()


In [0]:
## Get the Independent Features

X=df.drop('label',axis=1)

In [0]:
## Get the Dependent features
y=df['label']

In [0]:
X.shape

(18285, 20)

In [0]:
y.shape

(18285,)

WE require TF version > 2.0 to proceed further 

In [0]:
import tensorflow as tf

In [20]:
tf.__version__

'2.2.0'

Lets import required libraries

In [0]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [0]:
### Define Vocabulary size
voc_size=5000

### Onehot Representation

In [0]:
messages=X.copy()

In [25]:
messages['title'][1]

'FLYNN: Hillary Clinton, Big Woman on Campus - Breitbart'

In [0]:
messages.reset_index(inplace=True)

In [0]:
import nltk
import re
from nltk.corpus import stopwords

In [28]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

#Regular expression
#lowering the case
#spliting the word
#stemming


In [29]:
### Dataset Preprocessing
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    print(i)
    review = re.sub('[^a-zA-Z]', ' ', messages['title'][i]
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

Streaming output truncated to the last 5000 lines.
13286
13287
13288
13289
13290
13291
13292
13293
13294
13295
13296
13297
13298
13299
13300
13301
13302
13303
13304
13305
13306
13307
13308
13309
13310
13311
13312
13313
13314
13315
13316
13317
13318
13319
13320
13321
13322
13323
13324
13325
13326
13327
13328
13329
13330
13331
13332
13333
13334
13335
13336
13337
13338
13339
13340
13341
13342
13343
13344
13345
13346
13347
13348
13349
13350
13351
13352
13353
13354
13355
13356
13357
13358
13359
13360
13361
13362
13363
13364
13365
13366
13367
13368
13369
13370
13371
13372
13373
13374
13375
13376
13377
13378
13379
13380
13381
13382
13383
13384
13385
13386
13387
13388
13389
13390
13391
13392
13393
13394
13395
13396
13397
13398
13399
13400
13401
13402
13403
13404
13405
13406
13407
13408
13409
13410
13411
13412
13413
13414
13415
13416
13417
13418
13419
13420
13421
13422
13423
13424
13425
13426
13427
13428
13429
13430
13431
13432
13433
13434
13435
13436
13437
13438
13439
13440
13441
13442
13443
1

In [30]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

Lets pass each and every word into one hot encoding

In [33]:
onehot_repr=[one_hot(words,voc_size)for words in corpus] #list comprehension
onehot_repr

[[1644, 3139, 2920, 57, 186, 4150, 2794, 4732, 4261, 666],
 [605, 3428, 3639, 411, 1943, 2294, 4161],
 [2870, 264, 3417, 600],
 [300, 1329, 1675, 1325, 3296, 3466],
 [1501, 1943, 3400, 2544, 3098, 704, 1943, 735, 2324, 3403],
 [2229,
  906,
  4073,
  2980,
  3062,
  138,
  3905,
  2938,
  611,
  378,
  3183,
  4835,
  2868,
  2093,
  4161],
 [2656, 3137, 656, 2431, 2089, 4344, 885, 1821, 3162, 1870, 1937],
 [2216, 1935, 4349, 4048, 1183, 2817, 138, 813, 3162, 1870, 1937],
 [4741, 2812, 2685, 745, 572, 3964, 2068, 1471, 138, 3599],
 [2420, 2323, 173, 2189, 3884, 2598, 1813, 512],
 [2696, 3637, 4054, 1633, 2757, 2480, 1590, 2601, 3087, 2967, 4614],
 [1325, 1676, 186, 3964, 138, 1183],
 [1773, 4060, 745, 4984, 1432, 1878, 933, 199, 338],
 [67, 3892, 1248, 146, 4833, 1607, 3609, 3162, 1870, 1937],
 [4270, 3592, 4496, 488, 1009, 3162, 1870, 1937],
 [4457, 437, 3746, 184, 1504, 708, 4710, 3707, 2887, 4379],
 [1708, 1483, 3428],
 [4143, 4678, 1704, 1729, 138, 4565, 577, 4161],
 [2933, 203, 36

### Embedding Representation

using pad_sequences the length of the sentences is made common

In [34]:
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ... 4732 4261  666]
 [   0    0    0 ... 1943 2294 4161]
 [   0    0    0 ...  264 3417  600]
 ...
 [   0    0    0 ... 3162 1870 1937]
 [   0    0    0 ... 4782  194 2114]
 [   0    0    0 ... 3742 2224 2716]]


In [35]:
embedded_docs[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0, 1644,
       3139, 2920,   57,  186, 4150, 2794, 4732, 4261,  666], dtype=int32)

In [36]:
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 20, 40)            200000    
_________________________________________________________________
lstm (LSTM)                  (None, 100)               56400     
_________________________________________________________________
dense (Dense)                (None, 1)                 101       
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


In [37]:
len(embedded_docs),y.shape

(18285, (18285,))

converting embedded features in array

In [0]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [40]:
X_final.shape,y_final.shape

((18285, 20), (18285,))

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

### Model Training

In [48]:
### Finally Training
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
192/192 [==============================] - 7s 34ms/step - loss: 0.3404 - accuracy: 0.8407 - val_loss: 0.2125 - val_accuracy: 0.9145
Epoch 2/10
192/192 [==============================] - 6s 31ms/step - loss: 0.1506 - accuracy: 0.9405 - val_loss: 0.1931 - val_accuracy: 0.9228
Epoch 3/10
192/192 [==============================] - 6s 32ms/step - loss: 0.1129 - accuracy: 0.9591 - val_loss: 0.1977 - val_accuracy: 0.9211
Epoch 4/10
192/192 [==============================] - 6s 32ms/step - loss: 0.0839 - accuracy: 0.9703 - val_loss: 0.2172 - val_accuracy: 0.9128
Epoch 5/10
192/192 [==============================] - 6s 32ms/step - loss: 0.0688 - accuracy: 0.9751 - val_loss: 0.2454 - val_accuracy: 0.9148
Epoch 6/10
192/192 [==============================] - 6s 32ms/step - loss: 0.0468 - accuracy: 0.9847 - val_loss: 0.2933 - val_accuracy: 0.9147
Epoch 7/10
192/192 [==============================] - 6s 32ms/step - loss: 0.0337 - accuracy: 0.9883 - val_loss: 0.3543 - val_accuracy: 0.9115

### Adding Dropout 

In [0]:
from tensorflow.keras.layers import Dropout
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

### Performance Metrics And Accuracy

In [0]:
y_pred=model.predict_classes(X_test)

In [0]:
from sklearn.metrics import confusion_matrix

In [51]:
confusion_matrix(y_test,y_pred)

array([[3096,  323],
       [ 223, 2393]])

In [52]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9095277547638774